version: 2
jobs:
  build:
    working_directory: ~/lonamic
    docker:
      - image: circleci/node:8.4.0
    branches:
      only:
        - master
        - /v-.*/
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run cov
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ./coverage
          prefix: coverage
